src/FSharp.SystemTextJson/All.fs
src/FSharp.SystemTextJson/Union.fs
tests/FSharp.SystemTextJson.Tests/Test.Union.fs

Implement alternative union encodings

---

README.md
src/FSharp.SystemTextJson/All.fs
src/FSharp.SystemTextJson/Union.fs
tests/FSharp.SystemTextJson.Tests/Test.Union.fs

Previously, the `InternalTag` scheme hard-coded the tag name to be "Case". This PR makes the tag name configurable, but codes "Case" as the default, which should make this change fully backwards-compatible. This is done by adding a new argument to the set of `JsonFSharpConverter` constructors, along with a type alias to clarify what the argument does.
The original test suite passes, and four more test cases are added to be sure the new functionality
works.
This is... not a _naive_ approach per se, but it's a bit of a stab in the dark. I haven't yet updated the README, for instance, and don't want to until this approach has been reviewed and approved or updated. Very happy to switch approaches, too -- I'm not wed to this one. If this approach pleases, I'll push updates to the README + any …

Add support for changing the internal tag name

---

src/FSharp.SystemTextJson/All.fs
src/FSharp.SystemTextJson/Helpers.fs
src/FSharp.SystemTextJson/Options.fs
src/FSharp.SystemTextJson/Record.fs
src/FSharp.SystemTextJson/Union.fs
tests/FSharp.SystemTextJson.Tests/Test.Record.fs

There should probably be check on `[<AllowNullLiteral>]`(?) for the given type on the off chance somebody actually _wants_ nulls in their F# record type.

Enforce no nulls in record types unless type is FSharpOption

---

src/FSharp.SystemTextJson/All.fs
src/FSharp.SystemTextJson/Collection.fs
src/FSharp.SystemTextJson/Tuple.fs
tests/FSharp.SystemTextJson.Tests/Test.Collection.fs
tests/FSharp.SystemTextJson.Tests/Test.Record.fs

~Work in progress.~
~Need to implement the same behaviour for Sets, and perhaps `JsonStringMapConverter`  and `JsonMapConverter`?~
~I need some feedback before implementing the same behaviour there though.~ (Done!)
------
Ready for merge if everything checks out and looks ok 😁

Forbid nulls inside arrays, sets and tuples unless 'T isNullableFieldType

---

src/FSharp.SystemTextJson/Record.fs
tests/FSharp.SystemTextJson.Tests/Test.Record.fs

If an optional field is provided while a required field is missing for a record, it won't raise an exception and leave the required field null. I created a PR to fix it, and with a test case.

Fix bug: no exception for missing required field

---

src/FSharp.SystemTextJson/Helpers.fs
src/FSharp.SystemTextJson/Tuple.fs
tests/FSharp.SystemTextJson.Tests/Test.Collection.fs
tests/FSharp.SystemTextJson.Tests/Test.Union.fs

I was getting the error: `Unexpected null inside tuple-array. Expected type Unit, but got null.` when deserializing a type like `int * unit`. This PR removes null-checking for `unit` types inside a tuple and adds a test.
It's an odd thing to serialize, but I use `TenantId * RequestParameters` across all my [Bolero IRemoteService endpoints](https://fsbolero.io/docs/Remoting). In a couple of places, there are no `RequestParameters` so I use `TenantId * unit` here to maintain a consistent shape.
Without this PR, a `_ * unit` tuple serializes but does not deserialize.
**Edit:** A consistent shape is useful so I can write things like:
```
member inline this.Authorize<'req, 'resp when 'req : (member get_Item1 : unit -> TenantId)> (f : 'req -> Async<'resp>) : 'req -> Async<'resp> = ...
```

Fixes unit field deserialization

---

CHANGELOG.md
src/FSharp.SystemTextJson/All.fs
src/FSharp.SystemTextJson/Helpers.fs
src/FSharp.SystemTextJson/Options.fs
src/FSharp.SystemTextJson/Record.fs
src/FSharp.SystemTextJson/Union.fs
tests/FSharp.SystemTextJson.Tests/Test.Record.fs
tests/FSharp.SystemTextJson.Tests/Test.Union.fs

Example:
```fsharp
[<JsonFSharpConverter(unionTagName = "tag")>]
type Foo = Foo of x: int * y: string
// Default behavior:
let options = JsonSerializerOptions()
options.Converters.Add(JsonFSharpConverter(JsonUnionEncoding.InternalTag))
JsonSerializer.Serialize(Foo(1, "a")) // = {"Case":"Foo","x":1,"y":"a"]}
// With allowOverride:
let options = JsonSerializerOptions()
options.Converters.Add(JsonFSharpConverter(JsonUnionEncoding.InternalTag, allowOverride = true))
JsonSerializer.Serialize(Foo(1, "a")) // = {"tag":"Foo","x":1,"y":"a"]}
```

Fix #69: allow overriding converter options in attribute

---

build.fsx
docs/Customizing.md
src/FSharp.SystemTextJson/Helpers.fs
src/FSharp.SystemTextJson/Options.fs
src/FSharp.SystemTextJson/Union.fs
tests/FSharp.SystemTextJson.Tests/Test.Union.fs

I create a snapshot of a reader (a copy of structure) and parse it into a `JsonDocument` (which is a lazy operation) and do a union case lookup.
I have not added new tests but played with modification of existing (not committed) so add tests as appropriate.
Fixes #93

Implemented ability to deserialize discriminated unions regardless of union tag position

---

src/FSharp.SystemTextJson/FSharp.SystemTextJson.fsproj

Adds `GenerateDocumentationFile` Property to fsproj file. F# compiler
does not generate the .xml file by default, so
FSharp.SystemTextJson nuget packages didn't show any documentation in autocompletion.
Before:
After:

Add .xml with documentation comments to nupkg

---

src/FSharp.SystemTextJson/All.fs
src/FSharp.SystemTextJson/Options.fs
src/FSharp.SystemTextJson/Union.fs
tests/FSharp.SystemTextJson.Tests/Test.Union.fs

[#108] Add UnionFieldNamesFromTypes

---

src/FSharp.SystemTextJson/All.fs
src/FSharp.SystemTextJson/Options.fs
src/FSharp.SystemTextJson/Record.fs
tests/FSharp.SystemTextJson.Tests/Test.Record.fs

Add ways to include record properties (rather than just fields) in serialized JSON.
* Add option `includeRecordProperties: bool` to serialize properties of record types (unless ignored with `JsonIgnoreAttribute`).
* Serialize properties of record types that have `JsonIncludeAttribute` (even with `includeRecordProperties = false`).

Add options to serialize record properties

---

tests/FSharp.SystemTextJson.Tests/Test.Record.fs

Currently record members are ignored during serialization. I'm not sure if that's something you want to support, but if so, I thought I could at least provide the failing test. I've already tried to implement it myself but couldn't find a way without rewriting quite a bit of code, so maybe you've a better idea how to fix this issue. 
My workaround is currently to simply use a custom converter for the specific types. 
Thanks.

Support records with read only members

---

FSharp.SystemTextJson.sln
src/FSharp.SystemTextJson/Collection.fs
src/FSharp.SystemTextJson/FSharp.SystemTextJson.fsproj
src/FSharp.SystemTextJson/Helpers.fs
src/FSharp.SystemTextJson/JsonName.fs
src/FSharp.SystemTextJson/Record.fs
src/FSharp.SystemTextJson/Union.fs
tests/FSharp.SystemTextJson.Tests/Test.Record.fs
tests/FSharp.SystemTextJson.Tests/Test.Union.fs

```fsharp
type MyUnion =
| [<JsonName 1>] One of name: string
| [<JsonName 2>] Two of string
// eg: One "test" --> {"Case":1,"Fields":{"name":"test"}}
```
They are stringified when used as JSON property names (eg with `ExternalTag`: `{"1":["test"]}`).
```fsharp
type MyUnion =
| [<JsonName 1; JsonName "a">] One of string
| [<JsonName 2>] Two of string
```
```fsharp
type MyUnion =
| [<JsonName("name", "theName")>] One of name: string
// eg: One "test" --> {"Case":"One","Fields":{"theName":"test"}}
```

[#89] Add JsonName attribute for union cases with int or bool tags

---

src/FSharp.SystemTextJson/Collection.fs
src/FSharp.SystemTextJson/Record.fs
src/FSharp.SystemTextJson/Tuple.fs
src/FSharp.SystemTextJson/Union.fs
tests/FSharp.SystemTextJson.Tests/Test.Collection.fs
tests/FSharp.SystemTextJson.Tests/Test.Record.fs
tests/FSharp.SystemTextJson.Tests/Test.Union.fs

Fixes #158.
Throw a `JsonException` when trying to deserialize `null` into the following types:

Explicitly handle null values to throw an exception

---

src/FSharp.SystemTextJson/Record.fs
tests/FSharp.SystemTextJson.Tests/Test.Record.fs

Fixes #164.
This MR includes the regression test from #165.
It also fixes a few tests that should have been failing, but passed thanks to this bug.
cc @mlaily

fix #164: NRE on deserializing missing field with JsonIgnoreCondition.WhenWritingNull

---

tests/FSharp.SystemTextJson.Tests/Test.Record.fs

The record converter throws a NRE when trying to deserialize an empty json object, if the ignore nulls option is enabled.

Add failing unit test demonstrating an issue

---

src/FSharp.SystemTextJson/Record.fs
tests/FSharp.SystemTextJson.Tests/Test.Regression.fs

Fixes #172 and supersedes #173.

Fix NullReferenceException when serializing null record-typed record field

---

src/FSharp.SystemTextJson/Helpers.fs
src/FSharp.SystemTextJson/Options.fs
tests/FSharp.SystemTextJson.Tests/Test.Union.fs

Add optional argument `deserializeNullAsNone: bool` to option `.WithSkippableOptionFields(SkippableOptionFields)`.
```fsharp
let options =
JsonFSharpOptions.Default()
.WithSkippableOptionFields(SkippableOptionFields.Always, deserializeNullAsNone = true)
.ToJsonSerializerOptions()
JsonSerializer.Deserialize<{| x: int option|}>("""{}""", options)
// --> {| x = None |}
JsonSerializer.Deserialize<{| x: int option|}>("""{"x":null}""", options)
// --> {| x = None |}
```
Compare with the current, and now default `false` behavior:
```fsharp
let options =
JsonFSharpOptions.Default()
.WithSkippableOptionFields(SkippableOptionFields.Always)
.ToJsonSerializerOptions()
JsonSerializer.Deserialize<{| x: int option|}>("""{}""", options)
// --> {| x = None |}
JsonSerializer.Deserialize<{| x: int …
```

[#151] Add option to deserialize both null and missing as None

---

src/FSharp.SystemTextJson/Collection.fs
src/FSharp.SystemTextJson/Helpers.fs

Faster type comparisons. More work on compile time than runtime.
See:
https://sharplab.io/#v2:DYLgZgzgNALiCGEC2AfA9gBwKYDsAEAygJ4QxZICwAUNdcFjHjEdgMJpIbwBOAlhGhwFgaAO4AKAJR4AvHnHNsaMAB4wI+DAB8spiyzK1G7ZNo1z9RoqztOPfoIBiiGFN0AVfQDpxMyQv1DdTRNLSg9JVVg0NNzMzMgA

Faster type comparisons

---

src/FSharp.SystemTextJson/Helpers.fs
src/FSharp.SystemTextJson/Union.fs
tests/FSharp.SystemTextJson.Tests/Test.Union.fs

Enum-like unions can be used as dictionary keys
